language: objective-c
osx_image: xcode9

script:
- xcodebuild build -project LXExtension.xcodeproj -scheme LXExtension -sdk iphonesimulator
- xcodebuild build -project LXExtension.xcodeproj -scheme LXExtension -sdk iphoneos